Repository wirepas/tutorials, pull requests merged in 2020-01, with the labels that each got.

#79 Update README file
  README.md
Labels: documentation

#78 Update mosquitto/readme
  mosquitto/README.md
Labels: documentation

#77 Update fluentd conf
  fluentd/fluent.conf
Labels: documentation, tutorials/fluentd

#84 Update docker-compose.yml
  mysql/docker-compose.yml
Labels: tutorials/mqtt
